### PR TITLE
Dependencies and plugins are updated

### PR DESCRIPTION
**Pull request by aluscent**
Respective to dependencies and plugins updates, test packages also updated and refactored.

### CODE REVIEW

**Comment by jtnystrom** [comment]
Thanks for your work to help revive this library!

Did you try compiling and testing with sbt? The current version of sbt in this project (0.13.7-RC2) is ancient and runs with scala 2.10. Many of the plugins in project/plugins.sbt are not compatible with that version of sbt.

Can I suggest that we remove all the sbt plugins for now, i.e. delete project/plugins.sbt? They don't seem to be essential and we could reconsider later which ones should be in the project. When I did so, I was able to compile the project and run the tests (most are passing, but not all, but we can look into that later). (Note, I had to force JDK 8, the old version of sbt won't run on JDK 11)

As a next step we could also upgrade the version of SBT used (maybe as part of a port to Scala 2.12 which I think would be a good new minimal version to target?).

What do you think?

**Comment by aluscent** [comment]
Thank you for guiding me!

As you said, version of SBT is very old and needs to be updated. For now, I updated version of Scala from 2.11.7 to 2.11.12 (I didn't break the compatibility between versions). Also, updated all dependencies in "build.sbt" (which resulted in updating all test classes as the structure of scalatest package was changed).

I also removed some of plugins in "plugins.sbt" and updated the others. I didn't exactly know what each of them is doing. I will remove the whole file, we can add any plugin on demand.

In addition, I did some very tiny refactorings and import optimizations to make code more readable.

Now I will do another commit to update SBT version so we can start to port to Scala 2.12.

**Comment by jtnystrom** [comment]
Looks good, thanks!

**Comment by jtnystrom** [comment]
I think your change broke two of the unit tests in RNASequenceSpec.scala (you will see if you run `sbt test`) but it should be an easy fix.

**Comment by jtnystrom** [comment]
Fixed in 1d17be1cab9c1957c048f09599061f663168d16d

**Pull request merged**
